name: Build and Push Docker Image

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  setup-test-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Download test resources
        working-directory: tests
        run: |
          pip install requests
          python -c "from download_resources import download_resources; download_resources('../test_data')"

      - name: Upload test resources
        uses: actions/upload-artifact@v4
        with:
          name: test-resources
          path: ./test_data
  build-and-push:
    needs: [setup-test-data]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python + toml parser
        run: |
          python -m pip install --upgrade pip
          pip install toml nibabel numpy

      - name: Extract package version
        id: vars
        run: |
          PACKAGE_VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")
          PYTHON_VERSION=$(grep FROM Dockerfile | grep -oP 'python:\K[0-9]+\.[0-9]+' | tr -d '.')
          FLAVOR=cpu
          CUDA_VERSION=$(grep FROM Dockerfile_gpu | grep -oP 'cuda\K[0-9]+\.[0-9]+')
          echo "tag=v${PACKAGE_VERSION}-py${PYTHON_VERSION}-${FLAVOR}" >> $GITHUB_OUTPUT
          echo "tag_gpu=v${PACKAGE_VERSION}-py${PYTHON_VERSION}-cuda${CUDA_VERSION}" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image cpu
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: dbouget/raidionics-segmenter:${{ steps.vars.outputs.tag }}

      - name: Build Docker image gpu
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile_gpu
          push: false
          tags: dbouget/raidionics-segmenter:${{ steps.vars.outputs.tag_gpu }}

      - name: Create clean test environment
        run: |
          mkdir test_env
          cp -r tests test-env/

      - name: Download test resources
        uses: actions/download-artifact@v4
        with:
          name: test-resources
          path: ./test-env/unit_tests_results_dir

      - name: Integration tests
        env:
           GITHUB_ACTIONS: true
           IMAGE_TAG: ${{ steps.vars.outputs.tag }}
           IMAGE_TAG_GPU: ${{ steps.vars.outputs.tag_gpu }}
        run: |
          pip install pytest
          python -u -m pytest -s -vvv tests/local_docker_tests --log-cli-level=DEBUG

      - name: Push Docker image cpu
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: dbouget/raidionics-segmenter:${{ steps.vars.outputs.tag }}
          load: true

      - name: Push Docker image gpu
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile_gpu
          push: true
          tags: dbouget/raidionics-segmenter:${{ steps.vars.outputs.tag_gpu }}
          load: true